// <auto-generated />
using System;
using Amortization_System.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Amortization_System.Migrations
{
    [DbContext(typeof(AmorDbContext))]
    partial class AmorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Amortization_System.Models.Domain.Buyer", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("buyer_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("condo_unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("interest_rate")
                        .HasColumnType("float");

                    b.Property<double>("loan_amount")
                        .HasColumnType("float");

                    b.Property<DateTime>("payment_start")
                        .HasColumnType("datetime2");

                    b.Property<int>("payment_term")
                        .HasColumnType("int");

                    b.Property<string>("project_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Buyers");
                });
#pragma warning restore 612, 618
        }
    }
}
